### PR TITLE
Add LocationParam

### PR DESCRIPTION
**Pull request by VMRuiz**

### CODE REVIEW

**Comment by VMRuiz** [comment]
There seems to be some issues with mypy typing. Could you please recommend what's the best way to fix it?

**Comment by VMRuiz** [comment]
I added some exceptions in tests code for mypy errors because I couldn't make them work in the class definition itself. 
Also, there is another error about a licence in twine pipeline

**Comment by wRAR** [comment]
The twine problem is global and should be fixed by bumping the deps in `twinecheck`

**Review by Gallaecio — APPROVED** [review]
I guess docs will make more sense once we actually implement a location parameter for spiders.

**Pull request merged**
